name: mb
channels:
  - default
  - conda-forge
dependencies:
  - numpy=1.14
  - scipy=1.1
  - cython=0.28
  - qutip=4.3
  - pytest=3.8
  - pytest-cov=2.6
  - pytest-xdist=1.26
  - coveralls=1.7
  - sphinx=2
  - nbsphinx=0.4
  - jupyter=1.0
  - matplotlib=3.1
  - seaborn=0.9
  - pip:
    - recommonmark
    - sphinx_rtd_theme
