name: mb-docs
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - qutip=4.3
  - sphinx=2
  - nbsphinx=0.7
  - jupyter=1.0
  - matplotlib=3.1
  - seaborn=0.9
  - pip
  - pip:
    - recommonmark
    - sphinx_rtd_theme
